### ISSUE TITLE
[v8.2.0] ikvmc tool packages are missing runtime and java assemblies

### ISSUE THREAD

**Issue by viceice** [ikvm-revived/ikvm#104]
the `IKVM-8.2.0-tools-ikvmc-net461.zip` and also the netcoreapp3.1 zip files are missing the `IKVM.Runtime` and `IKVM.Java` assemblies, so they can't be used to compile the assemblies

**Comment by viceice** [comment]
`ikvm -?` didn't show me the `-runtime` parameter 🤔 i now copy those files to the `ikvmc` executable to build.

https://github.com/visualon/featureide.net/blob/main/tools/prepare.ps1

**Comment by viceice** [comment]
but it should work? i'll try it 🙃

**Comment by viceice** [comment]
![image](https://user-images.githubusercontent.com/1798109/178344180-4e78f849-e87e-4cb5-a174-4bb3c5dc4098.png)
😕

**Comment by wasabii** [comment]
Need to specify the path. -runtime:etc

**Comment by viceice** [comment]
🤦‍♂️

**Comment by wasabii** [comment]
I took a quick look at what you're doing. We haven't yet got around to writing up guidance or anything (so much to do), but I noticed you are publishing a NuGet package with an `ikvmc` generated assembly included. We recommend against this.

The idea here is that you are potentially not the only library on NuGet, or elsewhere, that might make use of org.sat4j. And that users of your package would then be unable to use any of those other packages. Because the two versions would clobber each other. Basically, if somebody else needed the same library, for another part of their project, which version should be picked?

MavenReference exists to solve this problem. And it'd be nice getting people using and testing it as it's incredibly new.

https://github.com/ikvm-revived/ikvm-maven

**Comment by viceice** [comment]
I know, sadly the featureide lib isn't yet published to maven.
maybe i remove the included sat4j libs again and use the seperate libs https://www.nuget.org/packages/org.sat4j.core

**Comment by wasabii** [comment]
Bundling ikvmc generated assemblies into NuGet packages is the same problem.

**Comment by viceice** [comment]
ok, so you suggest to build the assemblies on the fly. Not sure if i get licensing issues then? because my final app is closed source. 🤔

**Comment by wasabii** [comment]
For one, you can't publish closed source binaries on NuGet.org. It's prohibited by policy. So, assuming you don't mean your final app is there.

It's sort of on you to understand the licenses of the code you are using.
