### ISSUE TITLE
License change from version 8.1.5717 to 8.2

### ISSUE THREAD

**Issue by NullAndVoid** [ikvm-revived/ikvm#106]
I noticed a change in license from the former version to the latest.

![image](https://user-images.githubusercontent.com/6547490/178725422-99d8e262-4b58-4e66-9a3a-a1158cfacc75.png)
(nuget.com license link forwards you to this site)

As you can see version 8.1.5717 was under the zlib license plus GPL with exception (probably for the OpenJDK part). The code here in this repository from which 8.2 was built however is licensed under GPL only. This has a knock-on copyleft effect to all projects using IKVM, requiring them to license under GPL as well. 

Was this significant license change intentional or a mere oversight?

**Comment by NightOwl888** [comment]
The only [changes to the license](https://github.com/ikvm-revived/ikvm/commit/e48c507d3952d68a8d163a6daed6c6787dc0c66c) were:

1. Changed formatting to Markdown and renamed the file with an `.md` extension
2. Updated to the latest GPL 2.0 text (with updated mailing address)
3. Moved the Classpath Exception and other special notices to the bottom (in an attempt to get GitHub to detect the license)
4. Updated the copyright dates
5. Added additional contributors to the copyright

If any of these is your objection, please let us know.

It seems you cannot customize a GPL license in any way or GitHub will fail to recognize it. [GitHub's advice is to "remove complexity" from the main LICENSE file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#detecting-a-license) by moving it somewhere else to get it to detect the license, but I'm not sure separating the license into 2 files is the best way to handle this scenario. If you have any suggestions, we are open to ideas.

**Comment by wasabii** [comment]
I think ya'll are getting a wee bit confused about which portions of the software are licensed as what.

OpenJDK is licensed under GPLv2+CP, with a number of files under other licenses. There are bits of zlib stuff in there I believe. And probably other things.

The IKVM code contributed by Jeroen is zlib-licensed. And that hasn't changed. His files have notifications of such. Our existing LICENSE file goes over each part, with the last section representing the non-OpenJDK bits as best as we can.

Code contribute by Windward is assumed to also be zlib licensed, as they didn't really say otherwise, or alter any license notifications that I have found, and they did add their name to the Zlib bit in COPYRIGHT.

And same with my contributions. Zlib for now. Though I would very much not mind switching it MIT or something a little more well known for new contributions.

**Comment by wasabii** [comment]
@NullAndVoid  Where are you getting the idea that it was changed?

**Comment by wasabii** [comment]
Oh. Is it because @NightOwl888 changed the order in the file?

Hmm.

Yeah I might be against that. IKVM itself is zlib. OpenJDK is a third party, and so probably belongs lower.

**Comment by NullAndVoid** [comment]
@wasabii To be quite frank I only clicked the github license link and since it took me to the GPL page I assumed that this is now the license for the entire project. I neither checked individual files nor did I search the commit history.
So thanks to all of you for the clarification. That Winward didn't explicitly license their contribution is still a bit of a headache though. I do not have enough legal expertise to assess the potential dangers of that state. As you said @wasabii putting the whole IKVM part under MIT license would be the preferable solution. If that is even possible without getting everyone originally involved to sign it off.
Anyway from my side this issue can be considered closed.

**Comment by dkocher** [comment]
Clarified with a8efe3de0a3536ca9658bba16a96bee41b26447e.
