### ISSUE TITLE
 Method not found: 'Void System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.Security.AccessControl.FileSystemRights, System.IO.FileShare, Int32, System.IO.FileOptions)'.

### ISSUE THREAD

**Issue by ricksanchezisagoodman** [ikvm-revived/ikvm#14]
Hello, I am trying to use an library which is dependent with `IKVM`. After some stackoverflow [post](https://stackoverflow.com/questions/52560894/type-initialization-exception-on-pipeline-definition) google searching I found your repository. My problem is it seems the version of `IKVM.OpenJDK.Core` that I am using is trying to load the old `System.IO.FileStream` constructor which accepts `FileStreamSystemRights` as parameter. And since I am using .net core 2.1.1 there is no longer a constructor with that same parameter instead of FileSystemRights, it now uses FileShare as a parameter. Is there away for me to get the same IKVM dll but overide the FileStream constructor?

I am getting this exact error:

> `cli.System.MissingMethodException: Method not found: 'Void System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.Security.AccessControl.FileSystemRights, System.IO.FileShare, Int32, System.IO.FileOptions)'.
> 	at IKVM.NativeCode.java.io.FileDescriptor.open(Unknown Source)
> 	at java.io.FileDescriptor.open(FileDescriptor.java:315)
> 	at java.io.FileDescriptor.openReadOnly(FileDescriptor.java:287)
> 	at java.io.RandomAccessFile.open(RandomAccessFile.java:309)
> 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:234)
> 	at java.util.zip.ZipFile.<init>(ZipFile.java:189)
> 	at java.util.zip.ZipFile.<init>(ZipFile.java:162)
> 	at java.util.zip.ZipFile.<init>(ZipFile.java:108)
> 	at IKVM.Internal.VirtualFileSystem.Initialize(Unknown Source)
> 	at IKVM.Internal.VirtualFileSystem.GetVfsEntry(Unknown Source)
> 	at IKVM.Internal.VirtualFileSystem.GetBooleanAttributes(Unknown Source)
> 	at IKVM.NativeCode.java.io.Win32FileSystem.getBooleanAttributes(Unknown Source)
> 	at java.io.File.isDirectory(File.java:799)
> 	at java.io.File.toURI(File.java:700)
> 	at IKVM.Internal.AssemblyClassLoader.MakeResourceURL(Unknown Source)
> 	at IKVM.Internal.AssemblyClassLoader+AssemblyLoader.FindResources(Unknown Source)
> 	at IKVM.Internal.AssemblyClassLoader+<GetResourcesImpl>d__0.MoveNext(Unknown Source)
> 	at IKVM.Internal.AssemblyClassLoader+<GetResourcesImpl>d__0.MoveNext(Unknown Source)
> 	at IKVM.NativeCode.ikvm.runtime.AssemblyClassLoader.getResource(Unknown Source)
> 	at ikvm.runtime.AssemblyClassLoader.getResource(AssemblyClassLoader.java:65)
> 	at org.apache.log4j.helpers.Loader.getResource(Loader.java:97)
> 	at org.apache.log4j.LogManager.<clinit>(LogManager.java:103)
> 	at org.apache.log4j.LogManager.getLogger(LogManager.java:188)`

**Comment by ams-tschoening** [comment]
The following is related:

https://github.com/dotnet/runtime/issues/30435

You didn't say if you actually tried to use IKVM provided by this repo and if so, which branch. Your concrete problem should be fixed/worked around by using the branch [net_core_compat](https://github.com/ikvm-revived/ikvm/commits/net_core_compat).

**Comment by ricksanchezisagoodman** [comment]
Thank you @ams-tschoening I will check that out. Im sorry for the noob question.

**Comment by ams-tschoening** [comment]
> Im sorry for the noob question.

No problem, wasn't my intention to blame you. Feel free to reopen the issue as necessary.

**Comment by sreejukg** [comment]
> 
> 
> > Im sorry for the noob question.
> 
> No problem, wasn't my intention to blame you. Feel free to reopen the issue as necessary.



> 
> 
> The following is related:
> 
> [dotnet/runtime#30435](https://github.com/dotnet/runtime/issues/30435)
> 
> You didn't say if you actually tried to use IKVM provided by this repo and if so, which branch. Your concrete problem should be fixed/worked around by using the branch [net_core_compat](https://github.com/ikvm-revived/ikvm/commits/net_core_compat). A binary is available as well [somewhere else](https://github.com/ams-ts-ikvm/ikvm-bin/tree/net_core_compat).

Will this work with .Net Core? When I tried to add the dll from net_core_compact, I am getting the following error. 

The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'IKVM.OpenJDK.Core, Version=7.2.4630.5, Culture=neutral, PublicKeyToken=13235d27fcbfff58'

**Comment by ams-tschoening** [comment]
Looks the same to me and if you can't change the dependencies to use a more current IKVM, you won't be able to test if the mentioned branch works for you or not. Keep in mind, though,, that this branch is NOT considered production ready anyway.

https://github.com/ams-ts-ikvm/ikvm-bin/issues/2#issuecomment-728756178

**Comment by SushmaJShetty** [comment]
Do you know when this will be production ready? Will this be compatible for .NET Core 3.1? In dependent [dot net issues](https://github.com/dotnet/runtime/issues/30435), carlossanlop commented -  "we have added the implementation for Windows and it is available in 3.1", but similar to later comments it doesn't work in .NET Core 3.1. Any resolution in plan or ETA known for this?

**Comment by ams-tschoening** [comment]
Guten Tag SushmaJShetty,
am Donnerstag, 4. Februar 2021 um 16:35 schrieben Sie:

> Do you know when this will be production ready?[...]

If "this" means the concrete branch "net_core_compat", than most
likely never, because that approach has been pretty much abandoned and
was only part of some internal PoC anyway. Have a look at the
following for IKVM in general instead:

https://github.com/ikvm-revived/ikvm/issues/13
https://github.com/ikvm-revived/ikvm/issues/20
https://github.com/ikvm-revived/ikvm/issues/21
https://github.com/ikvm-revived/ikvm/pull/25#issuecomment-705608623

Mit freundlichen Grüßen

Thorsten Schöning

-- 
Thorsten Schöning
AM-SoFT IT-Service - Bitstore Hameln GmbH i.G. ist ein Mitglied der Bitstore Gruppe - Ihr Full-Service-Dienstleister für IT und TK

E-Mail: Thorsten.Schoening@AM-SoFT.de
Web:    http://www.AM-SoFT.de/

Telefon: 05151-  9468- 0
Telefon: 05151-  9468-55
Fax:     05151-  9468-88
Mobil:    0178-8 9468-04

AM-SoFT IT-Service - Bitstore Hameln GmbH i.G., Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB neu - Geschäftsführer: Janine Galonska


Für Rückfragen stehe ich Ihnen sehr gerne zur Verfügung.

Mit freundlichen Grüßen

Thorsten Schöning


Tel: 05151 9468 0
Fax: 05151 9468 88
Mobil: 
Webseite: https://www.am-soft.de 

AM-Soft IT-Service - Bitstore Hameln GmbH i.G. ist ein Mitglied der Bitstore Gruppe - Ihr Full-Service-Dienstleister für IT und TK

AM-Soft IT-Service - Bitstore Hameln GmbH i.G.
Brandenburger Str. 7c
31789 Hameln
Tel: 05151 9468 0

Bitstore IT-Consulting GmbH
Zentrale - Berlin Lichtenberg
Frankfurter Allee 285
10317 Berlin
Tel: 030 453 087 80

CBS IT-Service - Bitstore Kaulsdorf UG
Tel: 030 453 087 880 1

Büro Dallgow-Döberitz
Tel: 03322 507 020

Büro Kloster Lehnin
Tel: 033207 566 530

PCE IT-Service - Bitstore Darmstadt UG
Darmstadt
Tel: 06151 392 973 0

Büro Neuruppin
Tel: 033932 606 090

ACI EDV Systemhaus Dresden GmbH
Dresden
Tel: 0351 254 410

Das Systemhaus - Bitstore Magdeburg GmbH
Magdeburg
Tel: 0391 636 651 0

Allerdata.IT - Bitstore Wittenberg GmbH
Wittenberg
Tel: 03491 876 735 7

Büro Liebenwalde
Tel: 033054 810 00

HSA - das Büro - Bitstore Altenburg UG
Altenburg
Tel: 0344 784 390 97

Bitstore IT – Consulting GmbH
NL Piesteritz 
Piesteritz
Tel: 03491 644 868 6

Solltec IT-Services - Bitstore Braunschweig UG
Braunschweig
Tel: 0531 206 068 0

MF Computer Service - Bitstore Gütersloh GmbH
Gütersloh
Tel: 05245 920 809 3

Firmensitz: MF Computer Service - Bitstore Gütersloh GmbH, Gildestraße 25, 33442 Herzebrock-Clarholz
Geschäftsführer Janine Galonska

**Comment by Khalidaba** [comment]
> > > Im sorry for the noob question.
> > 
> > 
> > No problem, wasn't my intention to blame you. Feel free to reopen the issue as necessary.
> 
> > The following is related:
> > [dotnet/runtime#30435](https://github.com/dotnet/runtime/issues/30435)
> > You didn't say if you actually tried to use IKVM provided by this repo and if so, which branch. Your concrete problem should be fixed/worked around by using the branch [net_core_compat](https://github.com/ikvm-revived/ikvm/commits/net_core_compat). A binary is available as well [somewhere else](https://github.com/ams-ts-ikvm/ikvm-bin/tree/net_core_compat).
> 
> Will this work with .Net Core? When I tried to add the dll from net_core_compact, I am getting the following error.
> 
> The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'IKVM.OpenJDK.Core, Version=7.2.4630.5, Culture=neutral, PublicKeyToken=13235d27fcbfff58'
> 
> I think the legacy library that is dependant on IKVM, which is not in my control is trying to load the specific version of IKVM, which is failing. Any thoughts on this?

Hi @sreejukg i got the same pb .. do you find a solution ? how did you do to fix it?
