### ISSUE TITLE
No strong SecureRandom impls available

### ISSUE THREAD

**Issue by lprichar** [ikvm-revived/ikvm#149]
When I reference a (Kotlin) project via `<IkvmReference>` that calls `SecureRandom.getInstanceStrong()` then I get the following runtime error:

`NoSuchAlgorithmException: No strong SecureRandom impls available: NativePRNGBlocking:SUN`

Please advise as I'm new to IKVM, and this may be a problem with my project setup (e.g. I tried adding a NuGet reference to IKVM.OpenJDK.Security and IKVM.Runtime, but that appears to produce version mismatch issues).

**Comment by wasabii** [comment]
So, what's going on here is the distributed java.security file lists NativePRNGBlocking as the default strong provider. IKVM bundles the OpenJDK version of that from WIndows. The problem is the implementation from Windows is a no-op:

```

public final class NativePRNG {

    // return whether the NativePRNG is available
    static boolean isAvailable() {
        return false;
    }

    public static final class NonBlocking {
        static boolean isAvailable() {
            return false;
        }
    }

    public static final class Blocking {
        static boolean isAvailable() {
            return false;
        }
    }
}
```

So, NativePRNG is not supported on Windows in OpenJDK, and IKVM includes that.

Evaluating swapping it out for the Solaris version is a no-go. That implementation uses /dev/random, /dev/urandom, which would work on non-Windows, but also not work on Windows.

Looks like we need our own implementation of NativePRNG that dispatches over to .NET's secure version, which takes care of the xplat issues for us.

**Comment by lprichar** [comment]
Awesome explanation, thank you @wasabii, makes perfect sense

**Comment by wasabii** [comment]
I think the approach will not be to actually implement the sun NativePRNG class, but instead to create our own ikvm.security implementation, and ensure that's set as the strongest and specified in the policy file and SPI stuff.

**Comment by wasabii** [comment]
A quicker fix would be to set an insecure provider as the default. But that kinda sucks. Might do it in the meantime though.
