### ISSUE TITLE
[Tools] Tools for listing the jars when using ikvmc and IkvmReference

### ISSUE THREAD

**Issue by GeorgeS2019** [ikvm-revived/ikvm#157]
> [Reference ](https://github.com/ikvm-revived/ikvm/issues/156#issuecomment-1251522381)
> When converting a Java application with ikvmc, for best results, list the jars on the ikvmc command line in the same order that they appear in the Java application's classpath.

### Question

> I recall a tool, which I can not find now, previously provided for generating the listing of jars to obtain the best results

### Feature Request
> Ideally, we need similar tools perhaps provided by **Ikvm Visual Studio extension** for generating the listing of jars when using IkvmReference

**Comment by GeorgeS2019** [comment]
Perhaps relevant links
https://gist.github.com/byt3bl33d3r/30de727bf5bf28c8cbc45fa71cd51320

**Comment by wasabii** [comment]
This is not possible as JDK8 JAR files contain no dependency location information. Jigsaw (JDK9) augments them, optionally, with such. But that can't be relied upon to exist. And even then, the best that would get you is ordering with a topological sort. It wouldn't' actually find the JARs for you. And the order is an incredibly rare circumstance to matter.

The solution to this is to use a dependency management system, like Maven, which is why ikvm-maven exists.

**Comment by GeorgeS2019** [comment]
To explore further: [Maven doesn't always contain all dependencies](https://github.com/ikvm-revived/ikvm-maven/issues/2)
