### ISSUE TITLE
javac -version

### ISSUE THREAD

**Issue by GeorgeS2019** [ikvm-revived/ikvm#160]
The latest commit states
`
javac 1.8.0-internal
`
What would be a better way to state the version?

**Comment by NightOwl888** [comment]
Did you mean to use `ikvmc`?

`javac` is of course something we don't own and is versioned independently. BTW - Java version 1.8.0 == Java SE 8. That is just [the way the Java platform is versioned](https://www.oracle.com/java/technologies/javase/jdk8-naming.html).

**Comment by GeorgeS2019** [comment]
Right now, there is javac project and javac.exe  (Is ikvm's javac.exe == ikvmc.exe?)

**Comment by NightOwl888** [comment]
There was some discussion about renaming `ikvm.exe` as `java.exe` because it is intended as a direct replacement. Both accept similar parameters and will launch a .jar file and/or Java source code as an application (The .NET Core equivalent would be [dotnet run](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-run)).

However, `ikvmc.exe` has not been renamed `javac.exe` and it doesn't make much sense to do so because they have different purposes. [`javac.exe` compiles Java source code to byte code](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html), but `ikvmc.exe` converts Java byte code to CIL code. `ikvmc.exe` is modeled after `csc.exe` rather than `javac.exe`.
