### ISSUE TITLE
Unable to build on Jenkins

### ISSUE THREAD

**Issue by octavian-mirica** [ikvm-revived/ikvm#227]
IKVM 8.3.3

Hi,
I'm having some hard time getting my project to build on Jenkins.

My project is targeting .NET 6, but I also tried with .NET Core 3.1 and I'm getting the same errors from the picture below:
![image](https://user-images.githubusercontent.com/6584200/204322802-eda130ed-ab1d-466b-80d0-b50dc118b9e7.png)

What I did is pretty simple: I just added IKVM 8.3.3 package from Nuget server to my project, and use it to run some Java app that was already compiled into a .NET dll (using the same IKVM 8.3.3 with IkvmReference in another project).

My project (and also the Java app) builds and runs just fine locally, but when I try to build it on Jenkins server, it complains about those missing references that you can see in the picture (Microsoft.Build.Framework, mscorlib, netstandard, RoslynCodeTaskFactory).

Thank you for this library and I would appreciate any help or hint on understanding what's going on.

P.S.: I also tried to directly reference IKVM.Java.dll and IKVM.Runtime.dll (from .netcoreapp3.1 folder) in my project (so not adding IKVM 8.3.3 nuget package at all), but I got some nasty error in Visual Studio when I tried to add them into dependencies: "The reference is invalid or unsupported".

**Comment by wasabii** [comment]
My guess is your somehow not building on the Core SDK.

The x86 program files is weird.

**Comment by octavian-mirica** [comment]
Thanks for the reply.

Unfortunately, I don't know what that means.
My project is a .NET 6 SDK project that builds just fine on Jenkins, before I added the IKVM 8.3.3 nuget package to it.
I don't think it's related to targeting .NET 6, since I tried it with another project targeting .netcoreapp3.1 and I got the same errors on Jenkins.

Is there another way of referencing IKVM dlls at runtime in my project without adding the nuget package?
Maybe I could directly reference IKVM dlls (from the release build package) in my project.
If yes, which IKVM dlls do I need to add to references?
(This is how a colleague of mine used to do it when he used IKVM with .NET 4.7.2 few years ago.)

**Comment by wasabii** [comment]
Generally speaking, most people's issues come from exactly that: copying DLLs around and not just properly using the packages as they should be, and setting up weird environments.

That said, there's something with your build environment. Look at the path of MSBuild:

C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools.

This isn't real Visual Studio. I think it's the "Visual Studio Build Tools", which is a separate distribution of just the parts of VS that SHOULD be needed for MSBuild projects. Second, it's located in the (x86) folder. But real Visual Studio is 64-bit only now, and installs to the Progam Files diretory.

You say you're using a .NET Core project.

But you're building with the Visual Studio Build Tools. Not with the .NET Core SDK. To build with the .NET Core SDK you execute "dotnet build". You don't need any part of Visual Studio when building a pure .NET Core solution.

But you might need it if you're combining Framework-only projects with your solution: for instance, SSDT or vcxprojs. I have no idea if you're doing that.

Second, look at the errors. This is some pretty basic stuff. It can't find "netstandard"? That should be part of any recent MSBuild.

I am not familiar with the Build Tools for Visual Studio. It's been a decade since I've used them, since most modern build hosts needing VS are just configured with a full install of Visual Studio (since Community has been free for a very long time).

I would recommend you try to isolate the issue to your specific build environment: try installing the Build Tools on another machine, and seeing if you can build the project with them, or whether you get the same errors. Second, I'd examine whether you really need Visual Studio at all. Pure .NET Core solutions generally don't.

**Comment by octavian-mirica** [comment]
Thanks for your help, you were right: we're using MSBuild tools on our Jenkins server, not dotnet run.
