### ISSUE TITLE
Shadow Copying Assemblies and deployment of IKVM.Runtime.DLL

### ISSUE THREAD

**Issue by IgnacioHR** [ikvm-revived/ikvm#274]
When my application is deployed, the files `ikvm.properties` and the folder `ikvm` is also copied to the output folder together with the rest of the files generated by the compiler. At runtime, once IKVM.Runtime.DLL gets loaded, I found that this opens the file `ikvm\win7-x64\lib\tzdb.dat` that is located relative to the folder where IKVM.Runtime.DLL is.

Later, when the application starts (The application is Excel.exe so I can't modify things there) and the plug.in gets loaded, the file IKVM.Runtime.DLL is copied to a folder under `C:\Users\MyUser\AppData\Local\assembly\dl3\O4ZVNXL6.VM4\HRTDNB2W.31G\55c509cb\00dd0779_6c1ed901` that is the cache location according to the documentation [here](https://learn.microsoft.com/en-us/dotnet/framework/app-domains/shadow-copy-assemblies?redirectedfrom=MSDN) But the file `ikvm.properties` and the folder `ikvm` is not copied so the application fails to start.

In order to fix this situation I'm evaluating several alternatives:

1. Disable shadow copying by setting the [ShadowCopyFiles](https://learn.microsoft.com/en-us/dotnet/api/system.appdomainsetup.shadowcopyfiles) property to the string value "false". I don't know if I can do this from my own DLL and if doing so might have consequences on any other plug-ins loaded by Excel.
2. Wrap those files as resources in my DLL. This might work in Java when things are loaded from a "classpath" but I'm not sure if this can be done for loading `tzdb.dat` as it depends on how that file gets loaded.
3. Could those files be part of IKVM.Runtime.DLL instead of external resources? 
4.  Ask the community for additional ideas 👍 

Toughts?

**Comment by wasabii** [comment]
#167 

IKVM used to serve the java.home contents out of a VFS. Fake files. Stored inside a ZIP inside of a resource in the assembly. This would have worked for you.

However, we removed it. It very much broke expectations of a lot of Java code: that the code could examine System.getProperty("java.home"), and launch java.exe, javac.exec, etc, from it. And different platforms expect different contents. Basically, it didn't "look like" a real JVM. Also, users couldn't edit the various .property and .security files that existed along side the JVM.

Instead, IKVM.Runtime expects to be able to locate a property "Java Runtime Image", which contains the expected files. This is the folder you're referring to. This works great in modern .NET development, where the JRE is just a NuGet package containing content files. But yeah, I can see how shadow copying is an issue.

The other issue is that the JRE path itself is architecture dependent. Different versions of java.exe, javac.exe, etc, might be needed depending on the particular runtime you've launched IKVM within.

So here's how this works.

First off, upon first reading any system properties, the code in VMSystemProperties.java is executed. This attempts first to search for an ikvm.properties file. If found, the values inside that are loaded. It then checks whether the ikvm.home property has been defined. If not, it checks for ikvm.home.root, which points to the directory ABOVE ikvm.home. It then detects the current runtime RID (linux-x64, -arm, -arm64, win7-x64, win7-x86, etc). And it checks if ikvm.home.root contains one of those directories. If so, that path becomes ikvm.home.

It then validates ikvm.home to make sure it's a correct JRE directory.

ikvm.home then becomes java.home, but only if java.home isn't already set.

So you've got these two System properties: ikvm.home.root and ikvm.home. You can provide either in ikvm.properties, and it will figure out the rest.

Except you can't even do that.

So, you should be able to set the system properties for java.home yourself manually in your library.  Just make sure you do it before accessing any bit of IKVM.

java.lang.System.setProperty.

**Comment by IgnacioHR** [comment]
Thank you for the pointer to #167 I'm reading all them carefully and doing additional tests

**Comment by IgnacioHR** [comment]
Hmm... Even if i were able to set the "ikvm.home" manually to an absolute path, I've to solve another complex problem.

The project I've in Visual Studio to pack the Excel-Add in a Managed Module [Deploy an Office solution](https://learn.microsoft.com/en-us/visualstudio/vsto/deploying-an-office-solution?view=vs-2022) is not "prepared" to include files that are not "dll". I'm not saying this can't be done, I'm saying that this adds a very complex process compared to just relay in the discovery of dependant DLLs. Also There is the need to create special procedure in the installer to adjust the value of that absolute path.

I wonder if it could be possible to have both alternatives available so we can decide which one to use using the value of a single property more or less as follows:

1. VMSystemProperties.java checks for a property called "ikvm.javahomedll", the default value is "real". if there is no value (or the value is "real"), current process continues so it tries to find a file named "ikvm.properties"...
3. If the value of that property is "JDK" then a DLL is loaded that contains the "old" vfs.zip for the JDK.
4. If the value of that property is "JRE" then a DLL is loaded that contains the "old" vfs.zip for the JRE.

Something like that would cover most of the possible deployment scenarios.

I fully agree with the problems regarding exposed at #167 regarding the call of "java.exe" from inside IKVM. But in my use case, the problem is that my java library is using log2j (latest version) and the initialisation of log2j requires access to read the file  "tzdb.dat" which is not that expensive thing.

Thoughts?

**Comment by wasabii** [comment]
So, this project is a 20 year old project that has atrophied quite a bit. It's full of hacks and workarounds of unclear origin or reason. From stuff like the decision to implement an IOCP interface for NIO sockets, or a code base with a bunch of #IFDEF MONO. There's code in here that is working around bugs on .NET 2 SP1.

And it's been held back by this stuff. We've been stuck on a 10+ year old out of date version of JDK8 (managed to get that to a 7+ old out of date, yay!) Upgrading is hard for two reasons: a) there are so many weird hacks b) it's a naturally complicated library (compsci heavy) c) low contributors.  And I think the blame for (c) goes to (a) and (b).

So in order to cut down on the cruft, and make progress, I've taken a different stance from how it's been "run" for the last 10 years: reevaluate every line of code, or feature, from a more minimalist and modern approach. Ask the questions for existing code as if you're adding it for the first time.

So let me turn the question around on you.

Right now the OpenJDK libraries for java.io.File, java.io.FileSystem, java.nio.files.*, etc, just read from the File System. They're file libraries: they read from the file system. Every Java distribution on the planet expects a JRE (a directory with the lib, bin, etc). It is a modern and normal practice to distribute additional required files along with assemblies: so normal that NuGet added it as a feature twice (content, and in contentFiles in 2015). Thousands of libraries on Nuget.org distribute additional files: everything from dependent native libraries, to images, etc. The GAC is dead (as in MS recommends you avoid it).

It's basically a normal every day occurrence, that matches the expectations of both Java and .NET ecosystems.

So, you've got a request from somebody trying to write an Excel Add-in. He's asking you to insert if() statements at the top of every FileSystem related Java library, that checks if the path is inside some magic fake path on your file system (//.ikvm or /mnt/ikvm), and return results from a ZIP file embedded in an assembly instead. Basically fork a few dozen OpenJDK files. And write a big library to manufacture fake file paths: including ability to list, get the permissions of, check existence of, return file sizes of. Forking all of these files is going to make upgrading versions of the JDK much harder. And there's now going to be a lot of additional code that makes up fake stuff to test. And it sits at the top of every file access path.

What do you think of his request?

This isn't to be completely dismissive. It's just sort of the view I'm trying to take with this. I'm on a mission to cut down on the size of IKVM. So we can actually accomplish things that get us to the latest JDK 8. And Version 9 beyond that, etc. The project is huge and massive and confusing.

And I'm having a hard time justifying the work for something like this. I really think you should be able to distribute extra non-assembly files along with your add-in, and it can't be an abnormal thing in this day and age. Other people do it.

**Comment by IgnacioHR** [comment]
@wasabii your position is clear and this is always a good thing
