### ISSUE TITLE
Cannot make socket calls on linux, due to Winsock.java

### ISSUE THREAD

**Issue by vin2890** [ikvm-revived/ikvm#29]
Assumption is Winsock.java will need to be rewritten to account for Linux sockets, My question is if I modify this java file, how do i get it recompiled with the new class file and ultimately built with the solution? How do i add Java files to be compiled in the solution, is it a simple process?

**Comment by ams-tschoening** [comment]
Guten Tag Dominique Dunlap,
am Sonntag, 3. Januar 2021 um 16:46 schrieben Sie:

> Assumption is Winsock.java will need to be rewritten to account for
> Linux sockets, My question is if I modify this java file, how do i
> get it recompiled with the new class file and ultimately built with
> the solution? How do i add Java files to be compiled in the solution, is it a simple process?

I suggest simply searching the code base for "Winsock.java" and
"Winsock", this looks like a good way to see where this class is used
or socket assumptions regarding Windows are made externally to that
class.

Searching additionally reveals the file "ikvm\openjdk\allsources.lst"
on my version of the repo, which seems to be used for the build
currently. Though, the build has been changed in the past, so you
better make yourself familiar with the changes first.

https://github.com/ikvm-revived/ikvm/pull/25
https://github.com/ikvm-revived/ikvm/issues/20#issuecomment-633685407
https://github.com/ikvm-revived/ikvm/issues

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning
AM-SoFT IT-Service - Bitstore Hameln GmbH

E-Mail:  Thorsten.Schoening@AM-SoFT.de
Web:     http://www.AM-SoFT.de/

Telefon: 05151-  9468-55
Fax:     05151-  9468-88
Mobil:    0178-8 9468-04

Firmensitz: Bitstore IT-Consulting, Frankfurter Allee 285, 10317 Berlin
Steuernummer 037/230/30566, HR 27198, Amtsgericht Potsdam Geschäftsführer Janine Galonska

**Comment by wasabii** [comment]
I'm going to start tackling this I suppose, since it's pretty important.

So my general idea of the design is thus: OpenJDK has paths for Windows and Linux network support. IKVM decided to simply adopt the Windows side of the OpenJDK equation, since that was the closest to matching System.Net.Socket (given it's Windowsy origin). The OpenJDK C code which was the backend of the Windows support was converted to C#, as if it was acting against winsock.h.  And then the actual usage of winsock.h was subbed out by System.Net.Socket and friends.

It seems to me that the assumptions here remain mostly correct. .NET, even Core on Linux, is very similar to Winsock. Though there are a few little things that surface and probably need to be smoothed over. So we should probably keep the design as is, and just fix those things.

**Comment by wasabii** [comment]
#89  and #103 are tracking the work on this. I do have non-NIO sockets working on Linux now on a branch.
