### ISSUE TITLE
How do I help move this project forward?

### ISSUE THREAD

**Issue by spoiledsport** [ikvm-revived/ikvm#36]
Guys

I have been reading a lot of messages and I am still not clear on the where we are and what the plan is. I don't much going on for a while. I am really interested on helping on any way possible. I have some experience with IKVM, C#, etc.

**Comment by RockNHawk** [comment]
IKVM .NET sitll maintaining ? But I hear the another discontinued this project, it's a fork ?

**Comment by wasabii** [comment]
@spoiledsport 

Hello. We're back.

Getting ready to do a 8.2 release with Core support, and a completely new build system.

Next steps, of which help would be appreciated, is mostly going to be cleanup for a bit. The biggest thing is going to be untangling all of the #ifdefs, and pulling the code apart into modules that can be reused instead of recompiled.

From there, fixing up the compiler parts so they can cross-compile properly. Build Framework assemblies using Core versions of the compiler.

And after that, replacing what I think will be most of IKVM.Reflection with System.Metadata.

And then we have some hard decisions to make regarding whether we want to remove some features IKVM has that I think are of questionable benefit, such as various parts of the internal VFS.

And once it's cleaned up and slimmed down: JDK9+

**Comment by spoiledsport** [comment]
Which branch are we using for this?  I could try a couple of the open tasks on my free time

**Comment by wasabii** [comment]
develop

**Comment by NightOwl888** [comment]
> Which branch are we using for this? I could try a couple of the open tasks on my free time

Hi there, feel free to join into the conversation at https://discord.gg/MpzNd5Tk8P. We are getting ready for the first release on NuGet and could use some help kicking the tires to see if there are any issues.
