### ISSUE TITLE
Building IKVM - Step by step guide  (.Net Core)

### ISSUE THREAD

**Issue by oleneveu** [ikvm-revived/ikvm#42]
I managed to build IKVM, targeting .Net core 3.1.

I think that this basic step-by-step guide might be usefull to other people, but I don't know where to put it. 
If someone administering the repo find this interresting, he can move it to a more adequate place - and/or close the issue.

This guide applies to Windows.

Prepare for the build:
- Create a directory 'ikvm-revived' somewhere on your computer.
- Clone the 'ikvm' repository in that directory (https://github.com/ikvm-revived/ikvm.git)
- Clone the 'openjdk-8u45-b14-stripped' repository in that directory too (https://github.com/joegana/openjdk-8u45-b14-stripped.git). This repository contains the source code for the open jdk that will be used to build ikvm.
- Rename the 'openjdk-8u45-b14-stripped' directory to 'openjdk-8u45-b14'.
- You also need the Open JDK 8 binaries to compile. You can download it from here: https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot. You will then have to set your environment variables to target that jdk before the build (see: https://stackoverflow.com/a/52531093/2656835)
- Switch the 'ikvm' repo to the 'ikvm-build' branch, then pull the latest changes.

Build:
- Open a console in the 'ikvm' directory, set the JDK environment variables (see above), and run 'build.core.cmd'.
- The build process might take some time (about 5 minutes on a decent computer). 
- When the build process completes, the IKVM dlls and executables will be found in 'ikvm\bin\Release\netcoreapp3.1'.

Another branch ('ikvm-build2') is also available with several recent updates, including the strong name key.
I could not build that branch out of the box as the build ends-up with an error about the key. I managed to build it by reverting back to the commit '6db467e9d515a99789a76d2624d2bfcabf3df279' (second to last at the time I'm writing that guide) which actually excludes the strong name key.

Please note that although I ended up with a complete version of IKVM, I could not manage to compile successfully any jar using ikvmc.exe.

**Comment by NightOwl888** [comment]
You can update these instructions to build from the `master` branch now, as those PRs have been merged.

**Comment by NightOwl888** [comment]
IKVM has circular references. For example:

- IKVM.Runtime depends on IKVM.Runtime.JNI
- IKVM.Runtime.JNI depends on IKVM.Runtime

The IKVM.Runtime.FirstPass project is used to build a stub DLL that IKVM.Runtime.JNI can be built against. Then IKVM.Runtime is built against the real IKVM.Runtime.JNI dependency.

ikvmstub has a similar purpose, except the stub assemblies are dynamically generated rather than using MSBuild. More info about ikvmstub can be found at:

- https://sourceforge.net/p/ikvm/wiki/Tutorial/
- https://www.c-sharpcorner.com/UploadFile/abhijmk/ikvm-net-in-details/

**Comment by wasabii** [comment]
What about the references from IKVM.Runtime to IKVM.OpenJDK.Management, Misc, Util, etc? These are also circular? They're setup as actual <References> instead of <ProjectReference>, and won't resolve for me in VS, so something is up with em.

Any information on the build process for the OpenJDK bits? Seems to be the openjdk.csproj, but it looks like it's not actually using openjdk.dll, and instead doing the build with targets in openjdk.targets. There's a bunch of .lst and gen.lst files. What are these for? What builds them?

Guessing from looking at it:

allsources.lst is actually just a hand-built list of all of the .java files to be built. With some macro expansions with @@. This file gets transformed, somewhere, into allsources.gen.lst. Then it's used as the input into javac. Where do these output to? Who maintains this list? And then how do these make it into the eventual IKVM.OpenJDK.*.dll files? Somewhere I'd imagine there's a whitelist of which .class files end up in which .jar and then in which .dll, but I'm not seeing that.

So, it looks like instead of converting actual jar files from some OpenJDK release, what's going on is IKVM is building it all itself, and intermingling some additional java files of it's own? And in order to access .NET stuff from those class files, it's first using ikvmstub to generate stubs for some .NET libraries. These stubs are probably only used for the overridden classes?

So there's a lot of potential maintenance here in the override classes I suppose. And no doubt breakage between JDK versions.

What are the RSP files?

What is the openjdk.build file? Almost looked like a MSBuild file. But the case is so different from the standard that I'm not sure. Also, weird expansions going on.

**Comment by wasabii** [comment]
So what I'm getting from the layout of openjdk/ is that it's a lot of bit by bit hacking. Different things handled different ways. ProcessImpl.java.framework and ProcessImple.java.core for example, are copied to ProcessImpl.java depending on a Condition in MSBuild. I can imagine how this can break... actually.... I do believe multi-targeting is concurrent I believe.

Bunch of things using RegexTransform, sorta ad-hoc. A Target specifically for PropertyConstants.java transforming PropertyConstants.java.in.

It looks like the .class files are being output into the same directory. Not into some separate directory like obj. It's been a long time since I've done Java, so I can't remember if this is normal.

Since openjdk is producing multiple output DLLs... that's why ProjectReference isn't used. The ProjectReference spec doesn't support multiple output targets.

**Comment by NightOwl888** [comment]
All of the `.build` files are part of the original NAnt build and are no longer in use. They will be removed at some point, but for now it is helpful to have them to ensure the build with the .NET Core SDK contains all of the steps as the original NAnt build.

It looks like the .rsp and .lst files are still in use, but I am not sure whether they are used by the OpenJDK bit, the command line tools, or something else. Unfortunately, I haven't dug very deep into this, but #25 is where most of the changes happened for porting to .NET Core.

**Comment by NightOwl888** [comment]
> ProcessImpl.java.framework and ProcessImple.java.core for example, are copied to ProcessImpl.java depending on a Condition in MSBuild. I can imagine how this can break... actually.... I do believe multi-targeting is concurrent I believe.

I concur there are some bits that are shared between the .NET Framework build and .NET Core build that shouldn't be. I haven't attempted to do a solution build, but I suspect it won't work as-is because of shared bits in the obj directory.

This isn't necessarily blocking the NuGet packaging because it looks like that will need a separate .csproj/.targets file regardless of whether the solution build works or not. The output of each target framework goes into a separate folder below the /bin folder, so we can build one target, build the other target, and then do a solution level pack. But still, it would be better if we only had to do one build instead of two, which won't scale well if we add more targets.

Currently, the complete build is executed by running:

1. clean.core.cmd
2. build.core.cmd
3. build.framework.cmd

Then all of the artifacts will be below the top level bin folder.

We don't currently have the native bits building - see #23, but those will be output to the bin-x64 and bin-x86 directories.

> Bunch of things using RegexTransform, sorta ad-hoc. A Target specifically for PropertyConstants.java transforming PropertyConstants.java.in.

Yea, I saw that it was carried over, which isn't quite ideal. Ideally, we would get rid of all of the .in (template) files, but for now this will work.

> Since openjdk.csproj is producing multiple output DLLs... that's why ProjectReference isn't used. The ProjectReference spec doesn't support multiple output targets.
>
> I'm thinking this could be cleaned up.

ProjectReference doesn't work for circular dependencies, which is why the direct local DLL reference exists instead. Although, I agree if there is indeed a way to eliminate the circular dependency by adding another project, it could simplify the build quite a bit.

**Comment by NightOwl888** [comment]
> What is the openjdk.build file?

BTW - The [openjdk.build file](https://github.com/ikvm-revived/ikvm/blob/16b8889e1589fdda960b07458b723049a9543cf0/openjdk/openjdk.build) that is no longer in use was converted to the [openjdk.targets file](https://github.com/ikvm-revived/ikvm/blob/16b8889e1589fdda960b07458b723049a9543cf0/openjdk/openjdk.targets) for the new .NET SDK build system. This file is imported by the [openjdk.csproj project](https://github.com/ikvm-revived/ikvm/blob/16b8889e1589fdda960b07458b723049a9543cf0/openjdk/openjdk.csproj#L38).

**Comment by wasabii** [comment]
So..... only a subset of the IKVM DLLs have circular references right? Core, Management, Misc and Util, it looks like.

I think I'll take a stab at rebuilding the openjdk build, and just leave the Core/Management/Misc/Util stuff with a hack to do the circular stuff now. But, I'll split them out into separate projects (IKVM.OpenJDK.Core.msbuildproj, etc). That would be a good start towards organization, and getting it into a state where somebody like me can comprehend it.

**Comment by wasabii** [comment]
Does this new project yet have a central place to collab on conversations like this? A Discard? Gitter? Etc?

**Comment by NightOwl888** [comment]
> Does this new project yet have a central place to collab on conversations like this? A Discord? Gitter? Etc?

Nope. I haven't ever used such tools. Do you have experience setting one of them up?

**Comment by wasabii** [comment]
https://discord.gg/w26hNW7k

I'm guessing there's not much organizational structure at all happening right now eh?

**Comment by NightOwl888** [comment]
Hold on, I am trying to get verified.

**Comment by NightOwl888** [comment]
Argh, by the time I went through my SPAM software to recover the URL to verify the link, the discord invite was already expired. Could you send a new one?

**Comment by wasabii** [comment]
https://discord.gg/MpzNd5Tk8P  should never expire.

**Comment by NightOwl888** [comment]
Not sure what is going on here:

![image](https://user-images.githubusercontent.com/1538288/167742985-b67172f1-cf3c-4bb9-9837-1f2bd991eb2b.png)

I tried both FireFox and Chrome, but neither lets me pass this.

**Comment by NightOwl888** [comment]
Closing, as these build instructions are no longer relevant.
