### ISSUE TITLE
ikvmc fails to resolve .Net core assemblies

### ISSUE THREAD

**Issue by oleneveu** [ikvm-revived/ikvm#43]
Branch: 'ikvm-build2'
Commit '6db467e9d515a99789a76d2624d2bfcabf3df279'

After building the .Net core version (see: https://github.com/ikvm-revived/ikvm/issues/42#issue-1129670291), any attempt to use ikvmc fails with that error:

```
ikvmc, Version=8.5.0.3, Culture=neutral, PublicKeyToken=null
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.22\
3.1.22 64-bit

System.TypeInitializationException: The type initializer for 'IKVM.Internal.ClassLoaderWrapper' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'IKVM.Internal.PrimitiveTypeWrapper' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'IKVM.Internal.Types' threw an exception.
 ---> System.IO.FileNotFoundException: System.Runtime.Extensions, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
   at IKVM.Reflection.Universe.Load(String refname, Module requestingModule, Boolean throwOnError) in D:\Dev\Sources\ikvm-revived\ikvm\reflect\Universe.cs:line 834
   at IKVM.Reflection.Universe.Load(String refname) in D:\Dev\Sources\ikvm-revived\ikvm\reflect\Universe.cs:line 793
   at IKVM.Reflection.Universe.Import(Assembly asm) in D:\Dev\Sources\ikvm-revived\ikvm\reflect\Universe.cs:line 666
   at IKVM.Reflection.Universe.ImportImpl(Type type) in D:\Dev\Sources\ikvm-revived\ikvm\reflect\Universe.cs:line 644
   at IKVM.Reflection.Universe.Import(Type type) in D:\Dev\Sources\ikvm-revived\ikvm\reflect\Universe.cs:line 579
   at IKVM.Internal.JVM.Import(Type type) in D:\Dev\Sources\ikvm-revived\ikvm\runtime\IKVM.Runtime\vm.cs:line 488
   at IKVM.Internal.Types..cctor() in D:\Dev\Sources\ikvm-revived\ikvm\runtime\IKVM.Runtime\Types.cs:line 61
   --- End of inner exception stack trace ---
   at IKVM.Internal.PrimitiveTypeWrapper..cctor() in D:\Dev\Sources\ikvm-revived\ikvm\runtime\IKVM.Runtime\TypeWrapper.cs:line 3731
   --- End of inner exception stack trace ---
   at IKVM.Internal.ClassLoaderWrapper..cctor() in D:\Dev\Sources\ikvm-revived\ikvm\runtime\IKVM.Runtime\ClassLoaderWrapper.cs:line 140
   --- End of inner exception stack trace ---
   at IKVM.Internal.ClassLoaderWrapper..ctor(CodeGenOptions codegenoptions, Object javaClassLoader) in D:\Dev\Sources\ikvm-revived\ikvm\runtime\IKVM.Runtime\ClassLoaderWrapper.cs:line 117
   at IKVM.Internal.CompilerClassLoader..ctor(AssemblyClassLoader[] referencedAssemblies, CompilerOptions options, FileInfo assemblyPath, Boolean targetIsModule, String assemblyName, Dictionary`2 classes, Boolean compilingCoreAssembly) in D:\Dev\Sources\ikvm-revived\ikvm\ikvmc\CompilerClassLoader.cs:line 79
   at IKVM.Internal.CompilerClassLoader.CreateCompiler(CompilerOptions options, CompilerClassLoader& loader, Boolean& compilingCoreAssembly) in D:\Dev\Sources\ikvm-revived\ikvm\ikvmc\CompilerClassLoader.cs:line 2846
   at IKVM.Internal.CompilerClassLoader.Compile(String runtimeAssembly, List`1 optionsList) in D:\Dev\Sources\ikvm-revived\ikvm\ikvmc\CompilerClassLoader.cs:line 2576
   at IkvmcCompiler.Compile(String[] args) in D:\Dev\Sources\ikvm-revived\ikvm\ikvmc\Compiler.cs:line 320
   at IkvmcCompiler.Main(String[] args) in D:\Dev\Sources\ikvm-revived\ikvm\ikvmc\Compiler.cs:line 242
```

After some digging, when 'AssemblyResolver.AssemblyResolve()' is called to resolve 'System.Runtime.Extensions', 'universe.GetAssemblies()' only returns these references:
- [C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\netstandard.dll]
- [D:\Dev\Sources\ikvm-revived\ikvm\bin\Release\netcoreapp3.1\IKVM.Runtime.dll]
- [D:\Dev\Sources\ikvm-revived\ikvm\bin\Release\netcoreapp3.1\IKVM.Runtime.JNI.dll]

I managed to patch that issue by modifying 'AssemblyResolver.AssemblyResolve()':
(ikvmc/AssemblyResolver.cs, l.291)
```
	else
	{
		return null;
	}
```
is replaced with:
```
	else
	{
		foreach (string file in FindAssemblyPath(name.Name + ".dll"))
		{
			if (Match(AssemblyName.GetAssemblyName(file), name, ref previousMatch, ref previousMatchLevel))
			{
				return LoadFile(file);
			}
		}
		return null;
	}
```

I have a limited understanding of the whole process, so I am aware that this might not be the correct answer to that problem.
I still have an error after that and I am not able to say if this is a side effect of that patch.

**Comment by NightOwl888** [comment]
Well, it looks like you have stumbled upon the most serious issue we still have - the inability to select the appropriate DLL dependencies based on the code.

Your approach is good, but IMO we should strive to bridge the gap that we have between different flavors of .NET Core/.NET Standard by adding an extensible mapping feature of some sort. This will help us multi-target better as well as provide a mechanism to rewire DLL mapping for future versions of .NET Core. But I haven't dug down into the details of how to design such a feature. At the very least it should allow someone who isn't all that familiar with it to add another configuration for a new version of .NET that maps DLLs differently than .NET Core 3.1.

As of now, completing the work to make this build is up for grabs, so if you wish to attempt to complete the work on the [ikvm-build2 branch](https://github.com/ikvm-revived/ikvm/tree/ikvm-build-2) your assistance would be appreciated. For the SNK, there appears to be something broken with the `-keyfile` switch on `ikvmc`. There are basically 3 different ways to work around this:

1. Skip strong naming for the first preview releases and focus on the DLL mapping issue only for now
2. Use the `-key` switch for the time being, and work out how to automate adding the SNK to the local keystore (preferably on any OS). According to @joniles, it will build successfully with the SNK in the keystore.
3. Find the root cause of why the `-keyfile` switch is broken and fix it

**Comment by NightOwl888** [comment]
@oleneveu 

Thanks for the update.

> - It cannot build executables: When you build an executable from C# code, the output is actually a library and the executable is some kind of loader that is added at the end of the build process. The executable is not even managed code.
> - I also ran into an issue with ressources embedded in the jar: They fail to load when running the .Net Core assembly. I still haven't tried to compare with the .Net Framework version to ensure if this is a side effect to the port to .Net Core.

If by "some kind of loader" you mean a Java [ClassLoader](https://docs.oracle.com/javase/7/docs/api/java/lang/ClassLoader.html), do note that the closest equivalent in .NET is the [Assembly](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly?view=net-6.0) abstract class.

The resources are accessed using a "Classpath", which is like a folder structure in the `.jar` file. It can be used to handily load a resource file from the same "Classpath" as the current compiled class. .NET took a completely different approach - resources are stored in a dot delimited path structure that corresponds to the *physical* folder structure of the compiled project, but the classes are compiled into a *namespace*, which may be totally different than a resource path. I haven't looked into whether JNI has a way to resolve "Classpath"s, but it is probably worth investigating.

I made a [set of extension methods](https://github.com/NightOwl888/J2N/blob/main/src/J2N/AssemblyExtensions.cs) that can sort of mimic a "Classpath" approach to locating resources (in a .NET assembly), but it requires that the namespace of the type and the folder of the resource be somewhat similar in order to function (not sure whether this helps you or not).

Unfortunately, I haven't worked out exactly how a "Classpath" can be extended, but I do know that resources can be added to a "Classpath" by consumers of a `.jar` file. If you do manage to work out how, please share your findings (they are relevant for some of my other projects).

**Comment by NightOwl888** [comment]
As for the executables not functioning, in Java a `.jar` file can both be used as a library and host multiple insertion points for execution (see the `java` commands at the bottom of [this page](https://lucene.apache.org/core/4_8_0/core/index.html)). However, AFAIK in .NET, an assembly can only be compiled as a shared library *or* an executable, but not both.

To work around this limitation, we have been compiling as libraries and then building a separate executable assembly to consume them and call the `Main(object[] args)` methods of those libraries. I am not sure whether that makes sense for the output of `ikvmc`, though.

Worst case if you cannot figure it out, it would be better to have a version of IKVM that only works for libraries on NuGet.org than having no .NET Core support at all.

**Comment by oleneveu** [comment]
Sorry, I closed it by mistake...

**Comment by oleneveu** [comment]
It turns out that the issue with resources was not an issue with resources ;-)

The C# loader that I wrote is in C#, and set the culture for the process to the system culture, which in my case is not the default culture.
I managed to solve the problem by adding these lines to the loader:
```C#
Thread.CurrentThread.CurrentUICulture = CultureInfo.InvariantCulture;
Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
```
Another option was to reference explicitly `IKVM.OpenJDK.Localedata` by adding this line:
`sun.text.resources.fr.FormatData_fr fdfr = null;`
Having the assembly in the output directory was not enough.

Anyway I have done some cleanup and pushed my changes to my fork of the repo (https://github.com/oleneveu/ikvm, branch 'netcore3.1').

The executable (loader) added by msbuild is likely to be compiled on the fly. Using an hex editor shows that it includes the name of the assembly that it is supposed to load.
I believe that the source code must be in the sdk, and there must be an msbuild task somewhere to generate it.

> In .NET Core 3.1, it should be possible to make a stand-alone executable without any .json config files, but the option is not enabled by default. See https://stackoverflow.com/a/56092826.

This standalone executable is something different: For what I understood, it is some kind of archive that contains the executable and all the references (and certainly also the json files) and that self extracts itself on loading. Once again, there must be an msbuild task to build it.

**Comment by oleneveu** [comment]
> Although, I hope you aren't leaving it that way and are setting back to the original culture in a try/finally block. The [CultureContext class](https://github.com/NightOwl888/J2N/blob/main/src/J2N/Globalization/CultureContext.cs) can do this in a using block so it automatically switches both the culture and UI culture back to the original one.

Thanks for the tip. For now this is just a test project where I'm trying to figure out what works and what doesn't. I will start to care about the quality of the code when I will incorporate the converted assembly in the real project.
By the way, a using block is a try/finally behinds the scene so in the end this would be quite similar, but I agree that it is cleaner to use a dedicated disposable object.

Now I know that I have two options:
1. Ensure that the culture is 'Invariant'. 
2. Ensure `IKVM.OpenJDK.Localedata` is referenced, which should be the way to go in most situation.

In my case, the converted assembly is supposed to provide the same output, irrespective of the current culture (this is at least what the documentation states).

Thinking about it, there might be a problem behind that because loading `IKVM.OpenJDK.Localedata` requires a hack and I think that it was not the case for the .Net Framework version. The assembly just had to be in the output directory.
This might be related to the json file that lists the referenced assemblies.
I don't know if something should be done about that, because the cause of the issue is quite difficult to figure out and this might be a problem for many people.

On another subject, I have tried to build 'ikvm.exe' (which is not part of 'build.core.cmd' for some reason). The build succeeds but I had no luck when trying to run a jar: It throws an exception after a few lines of code.
This could have been an option to run an executable directly, but it seems that it will also require some work...

**Comment by NightOwl888** [comment]
> > Although, I hope you aren't leaving it that way and are setting back to the original culture in a try/finally block. The [CultureContext class](https://github.com/NightOwl888/J2N/blob/main/src/J2N/Globalization/CultureContext.cs) can do this in a using block so it automatically switches both the culture and UI culture back to the original one.
> 
> Thanks for the tip. For now this is just a test project where I'm trying to figure out what works and what doesn't. I will start to care about the quality of the code when I will incorporate the converted assembly in the real project. By the way, a using block is a try/finally behinds the scene so in the end this would be quite similar, but I agree that it is cleaner to use a dedicated disposable object.
> 
> Now I know that I have two options:
> 
> 1. Ensure that the culture is 'Invariant'.
> 2. Ensure `IKVM.OpenJDK.Localedata` is referenced, which should be the way to go in most situation.
> 
> In my case, the converted assembly is supposed to provide the same output, irrespective of the current culture (this is at least what the documentation states).

Google is your friend :).

I did a quick search and found that [ResourceBundle](http://www.avajava.com/tutorials/lessons/how-do-i-use-locales-and-resource-bundles-to-internationalize-my-application.html) is similar to .NET's `ResourceManager` class.

Furthermore, the [`.getBundle` method](https://docs.oracle.com/javase/7/docs/api/java/util/ResourceBundle.html#getBundle(java.lang.String)) works similarly to .NET in that it defaults to the *current* locale (which they call default) and has an overload that accepts a `Locale` to override.

> Thinking about it, there might be a problem behind that because loading `IKVM.OpenJDK.Localedata` requires a hack and I think that it was not the case for the .Net Framework version. The assembly just had to be in the output directory. This might be related to the json file that lists the referenced assemblies. I don't know if something should be done about that, because the cause of the issue is quite difficult to figure out and this might be a problem for many people.

What is the nature of the hack?

> On another subject, I have tried to build 'ikvm.exe' (which is not part of 'build.core.cmd' for some reason). The build succeeds but I had no luck when trying to run a jar: It throws an exception after a few lines of code. This could have been an option to run an executable directly, but it seems that it will also require some work...

Great info, thanks.

Looks like `ikvm.exe` is for "dynamic mode" of launching uncompiled code and `ikvmc` is for "static mode" where you compile into a .NET assembly for standalone operation.

https://www.c-sharpcorner.com/UploadFile/abhijmk/ikvm-net-in-details/

It doesn't look like `ikvmc` supports anything but DLL creation and it sounds like it is normal to have to tweak the ClassLoader to get it to load classes dynamically in certain cases.

That probably means that using `ikvm` is the only way to directly execute a Java app, but `ikvmc` can be used to compile it down to a DLL that can be wrapped with a .NET EXE with some extra configuration. I suspect the latter will be simpler to get working end to end, and it would also help to serve anyone who just depends on DLLs as well.

To run our tests which are DLLs with many dependencies we have to publish first to get all of the bits that are required for them to execute. `dotnet publish` is executed after `dotnet build`. So, the approach I think would work the best is to create a .NET project and do a build with `dotnet build`, analyze all of the build artifacts of `dotnet build`, and then try to duplicate them using `ikvmc` (analyzing the SDK source to find out how to best create them). Then try to run `dotnet publish` (including the `--no-build` switch) on those artifacts to see if we can get a successful publish to work.

This approach *should* work whether the output is a DLL or an EXE because `dotnet publish` is intended to do both, although each may have slightly different artifacts for `ikvmc` to duplicate from `dotnet build`.

But at the end of the day, if we can leverage `dotnet publish` to do the heavy lifting of preparing the assemblies to run, then we don't need to maintain that complex part of the process ourselves.

**Comment by wasabii** [comment]
The Java ClassLoader hierarchy can probably be rebuilt on the Core path around AssemblyLoadContext. It is conceptually similar now.

The main problem will be to group classes by assembly.

**Comment by NightOwl888** [comment]
@wasabii - Thanks. Would you mind sharing the details of the idea? Also, would you be willing to make a code contribution?

I agree that grouping classes by assembly is going to be a challenge. It would probably be worth looking into seeing if we can utilize the data that drives the [.NET API browser](https://docs.microsoft.com/en-us/teamblog/announcing-unified-dotnet-experience-on-docs). Ideally, we would be able to "export" the class/assembly mapping from a specific .NET version and put this metadata in a format that could be easily exported for any other .NET version that we target that is included as an embedded resource for that .NET Core version. There is probably more to it than that, but I haven't dug very deeply into this issue.

**Comment by wasabii** [comment]
Maybe. Evaluating a project that will require me to either port a large Apache project to C#, or find a solution like IKVM. Checking up on the status of IKVM at this point to see what state it's in.

I don't mean mapping external to the runtime itself. I mean that IKVM will need to provide a method like .getClassLoader() on each class type. And this will have to be tied to the java.lang.ClassLoader instance that "loaded the class", even though the class was loaded at runtime by an AssemblyLoadContext.

And the other way, that if the code instantiates a JARClassLoader or some such, that will have to make sure the dynamic types are loaded in an appropriate AssemblyLoadContext, which is itself tied back to the original java.lang.ClassLoader.

Haven't got into the code yet, but I know IKVM does already tie ClassLoader back into CLR stuff. Problem is it's all different on Core, and needs rework.

**Comment by NightOwl888** [comment]
One thing to note is that the `Assembly` abstract class in .NET is the rough equivalent to the `ClassLoader` class in Java.

**Comment by wasabii** [comment]
Not exactly. A ClassLoader can load classes, on the fly. That's the mismatch.

**Comment by wasabii** [comment]
That's the part that makes this difficult. In Java, classes are the top-level construct. ClassLoaders load classes on the fly as requested. And can be overridden to customize that loading. The basic one can simply load them from a disk, one by one, as requested. A JARClassLoader will load them as a group. Each dispatches to their parent ClassLoader to attempt to retrieve the class, if not available locally (or something even if, as global overrides). But of course, people can write their own.

The part that makes his difficult is you have to preserve all these use cases:

a) User compiles a JAR file into a DLL, but within that Java code invokes a new JARClassLoader instance, and specifies a path to a JAR, uses Java reflection to obtain a Class.
b) User uses FileClassLoader to load a specific .class file from disk.
c) User takes a class obtained from a class loader, and invokes .getParent on it, to obtain it's parent loader, and then invokes loadClass() on that specifically.
d) User obtains ClassLoader.default, and uses loadClass() to directly pass Java byte code (similar to Reflection.Emit).
e) User obtains a class, uses it's classLoader to obtain another class, then disposes of the ClassLoader, which releases all of the loadded classes.

Onward.

This stuff is already done in IKVM (I know from my experience a decade ago). But it will have to be very much redone to work on the new AssemblyLoadContext stuff. But it can be done BETTER, because AssemblyLoadContext more closely aligns (minus the hierarchy).

**Comment by NightOwl888** [comment]
Thanks for the info. I agree ClassLoader isn't exactly the same as Assembly. Although they serve a similar API surface, the implementation is not exactly the same. I found some more documentation about how this is implemented in .NET here: https://sourceforge.net/p/ikvm/wiki/ClassLoader/

It sounds like you have been deeper into this than I have, and have a clear understanding of the high-level concepts of what is required to make this work correctly in .NET core. And due to the fact that Assembly loading has been redesigned in .NET Core, I concur that some rework will need to be done.

For reference: https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext

**Comment by wasabii** [comment]
@richardschoen  Open a new bug then. I can't even figure out exactly what this one was about. Too many different issues people talked about.
