### ISSUE TITLE
Cipher.getInstance("AES/ECB/PKCS5Padding") Error

### ISSUE THREAD

**Issue by burakglc** [ikvm-revived/ikvm#70]
Hello.

Version 8.2.0-prerelease0379

cipher cipher = null;,

I define it as Cipher.getInstance("AES/ECB/PKCS5Padding"); I am getting error in method.
the error message is "The type initializer for 'javax.crypto.JceSecurity' threw an exception.' shaped.

![image](https://user-images.githubusercontent.com/67659988/171987754-8f3148a7-e8ed-4041-b029-f46439d3032f.png)

 cipher = Cipher.getInstance("AES/ECB/PKCS5Padding") 

An error occurs with this line of code.

**Comment by wasabii** [comment]
In develop I have fixed the type initializer exception. Was due to a problem opening compressed streams in the VFS. However, it now throws what appears to be a normal exception message saying "No such algorithm exists."

I need to dig into this more to understand how the JDK locates available algorithms, and why it thinks this one does not exist.

**Comment by wasabii** [comment]
Issue should be resolved in develop.

The JDK in `java.security.Security.getProviders()` reads the `lib/security/java.security` props file, which defines the class names of the security providers to enable. As long as these defined classes are on the classpath, the provider enumerates them for available algorithms. The issue was the VFS part again: it was opening the file, but not resetting the position of the returned memory stream. As such, when the stream made it's way over to Java, it only read the end and considered it an empty file, with no props, and thus no providers.

Pushing another prerelease with this fix.

**Comment by wasabii** [comment]
Note to self or others for later: The user really should be able to customize this file for an instance of the Runtime. We really need to think about what this means.
